### Get home page
GET https://basketball-players-api.onrender.com


### Get swagger api-docs 
GET https://basketball-players-api.onrender.com/api-docs



### Get all team players 
GET https://basketball-players-api.onrender.com/players


### Get team player by id
GET https://basketball-players-api.onrender.com/players/65b00fb8d78c5d8ebcb0435f


### Create team player
POST https://basketball-players-api.onrender.com/players/createPlayer HTTP/1.1
Content-Type: application/json

{
    "firstname": "Tim",
    "lastname": "Duncan",
    "age": 49,
    "height": "2.11m",
    "jerseyNo": 21,
    "position": "Power Forward / Center",
    "shoeSize": 13,
    "isCaptain": false,
    "timestamp": null
}


### Update team player by id
PUT https://basketball-players-api.onrender.com/players/65b00fb8d78c5d8ebcb0435f HTTP/1.1
Content-Type: application/json

{
    "firstname": "Lebron",
    "lastname": "James",
    "age": 39,
    "height": "2.6m",
    "jerseyNo": 24,
    "position": "Point Guard",
    "shoeSize": 13,
    "isCaptain": true,
    "timestamp": null
}


### Delete team player by id
DELETE https://basketball-players-api.onrender.com/players/65b14f1d57df66cacb1aa14a
